In [98]:
import pandas as pd

df1 = pd.read_csv("../../etl/raw_data/한국고전종합DB_관계망/itkc_events.csv")
df2 = pd.read_csv("../../etl/raw_data/한국고전종합DB_관계망/itkc_event_relations.csv")

In [99]:
df1.shape

(1542, 9)

In [100]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1542 entries, 0 to 1541
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   scope             1542 non-null   str
 1   event_id          1542 non-null   str
 2   event_name        1542 non-null   str
 3   subject_category  1542 non-null   str
 4   period            1542 non-null   str
 5   event_date        1532 non-null   str
 6   person_count      1542 non-null   int64
 7   related_event     605 non-null    str
 8   detail_url        1542 non-null   str
dtypes: int64(1), str(8)
memory usage: 108.6 KB

In [101]:
df1.head()

,scope,event_id,event_name,subject_category,period,event_date,person_count,related_event,detail_url
0,event_subject,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
1,event_period,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
2,event_period,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
3,event_period,ITKC_PH_1294A_0436,거란의 항복,전쟁,고려,1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
4,event_period,ITKC_PH_1294A_0437,최충헌의 사망,정치인,고려,1219년(고종 6) 9월,4,최씨무인정권,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...

In [102]:
df1 = df1.drop_duplicates(subset=["event_id"])

In [103]:
df1 = df1.drop(columns=['detail_url', 'person_count'])

In [104]:
df1.duplicated().sum()

np.int64(0)

In [105]:
df1.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   scope             600 non-null    str
 1   event_id          600 non-null    str
 2   event_name        600 non-null    str
 3   subject_category  600 non-null    str
 4   period            600 non-null    str
 5   event_date        595 non-null    str
 6   related_event     224 non-null    str
dtypes: str(7)
memory usage: 37.5 KB

In [106]:
df1 = df1.drop(columns=['scope'])

In [107]:
df1.shape

(600, 6)

In [108]:
df1.head()

,event_id,event_name,subject_category,period,event_date,related_event
0,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,고려거란전쟁
3,ITKC_PH_1294A_0436,거란의 항복,전쟁,고려,1219년(고종 6) 1월,고려거란전쟁
4,ITKC_PH_1294A_0437,최충헌의 사망,정치인,고려,1219년(고종 6) 9월,최씨무인정권
5,ITKC_PH_1294A_0438,의주적의 난,민란,고려,1219년(고종 6) 10월\r\n~ 1221년(고종 8) 3월,NaN
6,ITKC_PH_1294A_0439,이극인의 난,반란,고려,1224년(고종 11) 7월,최씨무인정권

In [109]:
df2.shape

(15392, 10)

In [110]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 15392 entries, 0 to 15391
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   scope               15392 non-null  str
 1   event_id            15392 non-null  str
 2   event_name          15392 non-null  str
 3   relation_type       15392 non-null  str
 4   person_id           15392 non-null  str
 5   person_name         15392 non-null  str
 6   related_event_id    0 non-null      float64
 7   related_event_name  0 non-null      float64
 8   evidence_url        0 non-null      float64
 9   detail_url          15392 non-null  str
dtypes: float64(3), str(7)
memory usage: 1.2 MB

In [111]:
df2.duplicated().sum()

np.int64(1556)

In [112]:
df2.head(5)

,scope,event_id,event_name,relation_type,person_id,person_name,related_event_id,related_event_name,evidence_url,detail_url
0,event_subject,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
1,event_subject,ITKC_PH_1294A_0435,강동성전투,사건인물,P058283,조충(趙冲),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
2,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
3,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P058283,조충(趙冲),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
4,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...

In [113]:
df2 = df2.drop_duplicates(subset=["event_id", "person_id"])

In [114]:
df2.info()

<class 'pandas.DataFrame'>
Index: 6918 entries, 0 to 14476
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   scope               6918 non-null   str
 1   event_id            6918 non-null   str
 2   event_name          6918 non-null   str
 3   relation_type       6918 non-null   str
 4   person_id           6918 non-null   str
 5   person_name         6918 non-null   str
 6   related_event_id    0 non-null      float64
 7   related_event_name  0 non-null      float64
 8   evidence_url        0 non-null      float64
 9   detail_url          6918 non-null   str
dtypes: float64(3), str(7)
memory usage: 594.5 KB

In [115]:
df2.tail()

,scope,event_id,event_name,relation_type,person_id,person_name,related_event_id,related_event_name,evidence_url,detail_url
14472,event_subject,ITKC_PH_1305A_0334,심수경의 과거 동기,사건인물,P056339,조보(趙溥),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
14473,event_subject,ITKC_PH_1305A_0334,심수경의 과거 동기,사건인물,P058193,조징(趙澄),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
14474,event_subject,ITKC_PH_1305A_0334,심수경의 과거 동기,사건인물,P066169,홍천민(洪天民),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
14475,event_subject,ITKC_PH_1305A_0334,심수경의 과거 동기,사건인물,P066576,황림(黃琳),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
14476,event_subject,ITKC_PH_1305A_0334,심수경의 과거 동기,사건인물,P066959,황응규(黃應奎),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...

In [116]:
df2 = df2.drop(columns=['scope', 'detail_url', 'evidence_url'])

In [117]:
df2.head()

,event_id,event_name,relation_type,person_id,person_name,related_event_id,related_event_name
0,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN
1,ITKC_PH_1294A_0435,강동성전투,사건인물,P058283,조충(趙冲),NaN,NaN
6,ITKC_PH_1294A_0436,거란의 항복,사건인물,P011067,김취려(金就礪),NaN,NaN
7,ITKC_PH_1294A_0436,거란의 항복,사건인물,P058283,조충(趙冲),NaN,NaN
8,ITKC_PH_1294A_0437,최충헌의 사망,사건인물,P008037,김약선(金若先),NaN,NaN

In [118]:
df2['related_event_id'].nunique()

0

In [119]:
df2['related_event_name'].nunique()

0

In [120]:
df2['relation_type'].unique()

<StringArray>
['사건인물']
Length: 1, dtype: str

In [121]:
df2 = df2.drop(columns=['related_event_id', 'related_event_name','relation_type'])

In [122]:
df2.head()

             event_id event_name person_id person_name
0  ITKC_PH_1294A_0435      강동성전투   P009535    김인경(金仁鏡)
1  ITKC_PH_1294A_0435      강동성전투   P058283      조충(趙冲)
6  ITKC_PH_1294A_0436     거란의 항복   P011067    김취려(金就礪)
7  ITKC_PH_1294A_0436     거란의 항복   P058283      조충(趙冲)
8  ITKC_PH_1294A_0437    최충헌의 사망   P008037    김약선(金若先)

In [123]:
df1.to_csv("../../storage/neo4j/neo4j_import/event.csv", index=False)
df2.to_csv("../../storage/neo4j/neo4j_import/event_relation.csv", index=False)