In [3]:
import pandas as pd

term = pd.read_csv('../../../etl//raw_data/교육부 국사편찬위원회_한국역사용어시소러스 정보_20211028 (1).csv')

event = pd.read_csv('../../../etl/raw_data/한국고전종합DB_관계망/itkc_events.csv')

event_rela = pd.read_csv('../../../etl/raw_data/한국고전종합DB_관계망/itkc_event_relations.csv')

In [4]:
event.head()

,scope,event_id,event_name,subject_category,period,event_date,person_count,related_event,detail_url
0,event_subject,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
1,event_period,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
2,event_period,ITKC_PH_1294A_0435,강동성전투,전쟁,고려,1218년(고종 5) 12월\r\n~ 1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
3,event_period,ITKC_PH_1294A_0436,거란의 항복,전쟁,고려,1219년(고종 6) 1월,2,고려거란전쟁,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
4,event_period,ITKC_PH_1294A_0437,최충헌의 사망,정치인,고려,1219년(고종 6) 9월,4,최씨무인정권,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...

In [5]:
event_rela.head()

,scope,event_id,event_name,relation_type,person_id,person_name,related_event_id,related_event_name,evidence_url,detail_url
0,event_subject,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
1,event_subject,ITKC_PH_1294A_0435,강동성전투,사건인물,P058283,조충(趙冲),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
2,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
3,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P058283,조충(趙冲),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...
4,event_period,ITKC_PH_1294A_0435,강동성전투,사건인물,P009535,김인경(金仁鏡),NaN,NaN,NaN,https://db.itkc.or.kr/people/viewEvnt?gubun=ev...