In [9]:
import pandas as pd
import json

In [ ]:
df = pd.read_csv("./term_name_matches.csv")
df_n = df[df.match_status == 'none']
# 읽어올 JSONL 파일 경로
file_path = "../../../raw_data/한국민족문화대백과사전/articles_detail.jsonl"

# lines=True 옵션을 반드시 주어야 합니다.
data_1 = pd.read_json(file_path, lines=True)

In [16]:
df_n

,canonical_term,category,count,problem_ids,match_key,thesaurus_term_ids,encyclopedia_eids,in_thesaurus,in_encyclopedia,match_status
2689,과거제,제도,23,"['cj_v41_0024', 'cj_v41_0030', 'cj_v41_0055', ...",과거제,NaN,NaN,False,False,none
2690,김춘추,인물,19,"['cj_v41_0006', 'cj_v41_0050', 'cj_v41_0291', ...",김춘추,NaN,NaN,False,False,none
2691,동북 9성,유적,16,"['cj_v41_0014', 'cj_v41_0111', 'cj_v41_0202', ...",동북구성,NaN,NaN,False,False,none
2692,미쓰야 협정,조약,15,"['cj_v41_0040', 'cj_v41_0280', 'cj_v41_0325', ...",미쓰야협정,NaN,NaN,False,False,none
2693,범금 8조,제도,15,"['cj_v41_0097', 'cj_v41_0145', 'cj_v41_0475', ...",범금팔조,NaN,NaN,False,False,none
...,...,...,...,...,...,...,...,...,...,...
4756,연잉군,인물,1,['cj_v41_1503'],연잉군,NaN,NaN,False,False,none
4757,눌지왕,인물,1,['cj_v41_0003'],눌지왕,NaN,NaN,False,False,none
4758,회령부,기관,1,['cj_v41_1502'],회령부,NaN,NaN,False,False,none
4759,나선,국가,1,['cj_v41_1502'],나선,NaN,NaN,False,False,none
4760,영고탑,지명,1,['cj_v41_1502'],영고탑,NaN,NaN,False,False,none

In [24]:
tt = data_1[data_1.headword.str.contains('눌지')].articleAliases.iloc[0]

In [36]:
[j.split("ː")[1] if 'ː' in j else j for i in tt for j in i.values()]

['눌지왕', '이칭']

In [ ]:
data_1[data_1.headword.str.contains('눌지')]

,eid,url,headword,origin,headwordOrigin,field,primaryTypePartA,primaryTypePartB,primaryType,secondaryType,...,reference,writerInfo,lastModifiedTime,headMID,headMedia,articleAliases,articleAttributes,hashtags,relatedArticles,relatedMedias
23640,E0013294,https://encykorea.aks.ac.kr/Article/E0013294,눌지마립간,訥祇麻立干,눌지마립간(訥祇麻立干),역사/고대사,인물,전통 인물,인물/전통 인물,NONE,...,"- 『삼국사기』\n- 『삼국유사』\n- ｢신라상대왕위계승연구｣(이종욱, 영남대학교민...",김영하,2022-09-08T10:14:17.6,00000000-0000-0000-0000-000000000000,NaN,"[{'word': '눌지왕', 'aliasType': '일반ː이칭'}]","[{'groupName': '인물/전통 인물', 'attrName': '성별', '...",[],"[{'targetEID': 'E0012440', 'targetUrl': 'https...",[]